### PR TITLE
add auth_http_header

### PR DESCRIPTION
**Pull request by tjikkun**
Add the ability to specify auth_http_header in mailhost

### CODE REVIEW

**Comment by wyardley** [comment]
@tjikkun: can you add tests for this?
It would probably just be a few lines in `spec/defines/resource_mailhost_spec.rb`

**Comment by tjikkun** [comment]
@wyardley Thanks for looking, I have added tests now

**Comment by wyardley** [comment]
Thanks for the quick changes! Looks good to me

**Comment by dol** [comment]
The documentation of the class parameter is missing in the manifests/resource/mailhost.pp file. If it's ok I'll add it in the #769 rebase.

**Comment by wyardley** [comment]
@dol: adding docs is always a good thing. We're hoping to rework the docs in general, since the module obviously could be better documented, but definitely feel free to add it in your PR.

**Pull request merged**
