### PR TITLE
Use HTTPS for Yum repositories

### PR DESCRIPTION
**Pull request by mhutter**
#### Pull Request (PR) description
Use HTTPS instead of HTTP for yum repositories

#### This Pull Request (PR) fixes the following issues
None. I actually implemented it because I use this module from a location where only HTTPS is required, but it's good practice to use HTTPS when available anyway!

### CODE REVIEW

**Comment by mhutter** [comment]
origin was up to date, but I totally missed the specs. Test still fail though, with (seemingly?) unrelated errors

**Comment by ekohl** [comment]
Ah, https://github.com/voxpupuli/puppet-nginx/pull/1235 hasn't been merged yet.

**Comment by ekohl** [comment]
That's merged now :)

**Comment by mhutter** [comment]
Rebased, now the tests worked as well!

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
