### PR TITLE
Use SSL for nginx APT repository

### PR DESCRIPTION
**Pull request by saz**
The nginx APT repository is currently not using https.
This PR will fix this.

### CODE REVIEW

**Comment by wyardley** [comment]
@saz: at a minimum, the spec tests will probably need to be updated for us to merge this (to reflect the changed URLs). 
https://github.com/voxpupuli/puppet-nginx/blob/master/.github/CONTRIBUTING.md
has some info on how to run tests, etc. (any additional commits should be squashed down to 1).

**Comment by wyardley** [comment]
Technically, it just needs the tests to be updated, but I'm adding the 'needs tests' flag until the tests are passing.

**Comment by xaque208** [comment]
I believe this will require the apt-transport-tls package to function correctly, which is not installed by default.

**Comment by wyardley** [comment]
@xaque208 Ah, didn't realize that, but that may be another reason not to do this.

**Comment by wyardley** [comment]
Assuming what @xaque208 said is correct, I think it makes sense to either a) not implement this, or b) make it a configurable option, defaulting to off. If you want to make a pass at implementing b), I think this can be discussed, but there will need to be test cases for both.

Maybe a boolean option in `nginx` (not `nginx::config`), called something like `apt_use_ssl`, defaulting to `false`?

**Comment by wyardley** [comment]
@xaque208: looking again, we're already using https for passenger repo, and there's already a:
`        ensure_packages([ 'apt-transport-https', 'ca-certificates' ])` in `package/debian.pp`, so this is already taken care of, I think, if the OP just changes the spec tests.

**Comment by saz** [comment]
I'll change the pr asap. Sorry for missing this! 


Sent using Boxer

On 28 Oct 2016 8:29 PM, Will Yardley <notifications@github.com> wrote:

@xaque208: looking again, we're already using https for passenger repo, and there's already a:
ensure_packages([ 'apt-transport-https', 'ca-certificates' ]) in package/debian.pp, so this is already taken care of, I think, if the OP just changes the spec tests.

**Comment by xaque208** [comment]
Does `ensure_packages()` just add the resources to the catalog if they are not already present? @wyardley

**Comment by xaque208** [comment]
@wyardley Never mind, read the code and answered my own question.

**Comment by wyardley** [comment]
@xaque208 Yeah, just noticed this offhand when I was testing some unrelated acceptance test stuff related to Ubuntu 16; the Passenger repo is already using https (and works in the acceptance tests), so I think this will work as-is. Still need to work out whether it's worth embedding the GPG key in the package *and* whether it's feasible / practical to deal with GPG key expiration directly in the module.

@saz: thanks! I mentioned it above, but make sure to squash the commits.

There are a couple PRs that are pending that have a bit of overlap, but I think (hope) they won't conflict.

**Comment by wyardley** [comment]
@saz: have you had a chance to update the tests?

**Comment by saz** [comment]
@wyardley should be working now.

**Comment by wyardley** [comment]
👍

**Pull request merged**
