### PR TITLE
Add location defaults to init and server resource

### PR DESCRIPTION
**Pull request by dol**
By adding location defaults it's possible to overwrite location
value like 'index_files'.

Related to #1068

### CODE REVIEW

**Comment by dol** [comment]
My goal is to avoid [config_pitfalls](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/). I'd like to clear the `www_root` and `index_files` when using locations in the context of `nginx::nginx_servers`(hiera).

**Comment by elmobp** [comment]
+1!

**Comment by wyardley** [comment]
This seems sane to me (though I'd love to see someone take a stab at reworking the configs in a way that avoids so much duplication in a cleaner way).

@dol can you rebase?

**Comment by wyardley** [comment]
@dol I think the extra commit ends up pulling in other changes, so if possible, can you reset back, then rebase, then force push?

**Comment by dol** [comment]
@wyardley It took some time to get what you were asking for. But the merge commit is cleaned up.

**Comment by oranenj** [comment]
Looks good to me. Thanks :)

**Pull request merged**
