### PR TITLE
uwsgi: allow custom uwsgi_param directives

### PR DESCRIPTION
**Pull request by darken99**
This patch allows custom uwsgi params to be added with uwsgi_param, same way fastcgi_param work.

### CODE REVIEW

**Comment by wyardley** [comment]
@darken99: can you resolve the conflicts and add tests if you want this to be merged? Let us know if you need help figuring out what / how to test.

**Comment by darken99** [comment]
@wyardley: conficts resolved. Please provide info how to test and what.

**Comment by wyardley** [comment]
I think the tests should be more or less the same as
https://github.com/voxpupuli/puppet-nginx/blob/master/spec/defines/resource_location_spec.rb#L506-L535

Then, before you commit, try:
```
$ bundle install
$ bundle exec rake rubocop
$ bundle exec rake spec
```
and resolve any warnings or test failures. You can also run
```
$bundle exec rspec spec/defines/resource_location_spec.rb(:xyz)
```
(with optional line number xyz) to run the tests in that file while you're testing on it.

**Comment by wyardley** [comment]
Please squash the commits into one (and also note comment in https://github.com/voxpupuli/puppet-nginx/pull/767#pullrequestreview-3376149)

Did the notes about testing (https://github.com/voxpupuli/puppet-nginx/pull/767#issuecomment-252300584) help? If you can get some things roughed in, we can help if there are any issues.

**Pull request closed without merging**
