### PR TITLE
Release 3.2.1

### LINKED ISSUE #1469: Release with stdlib up to 9.0.0
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby: any
- Distribution: any
- Module version: 3.2.0

## How to reproduce (e.g Puppet code you use)

I have some failing acceptance tests in https://github.com/voxpupuli/puppet-prometheus/pull/583#discussion_r718877781, with stdlib updated to version 9 it would work.

## What are you seeing

```
  Error: Could not install module 'puppet-nginx' (v3.2.0)
    The requested version cannot satisfy one or more of the following installed modules:
      puppetlabs-stdlib, installed: 8.0.0, expected: >= 5.0.0 < 8.0.0
```

## Any additional information you'd like to impart

the needed change is already included. a new version would fix my case.

### PR DESCRIPTION
**Pull request by baurmatt**
#### This Pull Request (PR) fixes the following issues
Fixes #1469

### CODE REVIEW

**Comment by root-expert** [comment]
I believe this could be a patch release.
CentOS 7 specs have been failing for a while and are blocking several PRs. Never achieved to fix them, if you have any idea :D

**Comment by baurmatt** [comment]
I've looked into the CentOS 7 tests but have no idea what the problem might be 🤷 

Happy to change this to a patch release if you want.

**Comment by smortex** [comment]
We can release a patch version quickly to unblock consumers of the module.

I am looking into fixing CI in #1473 ATM with trial and errors.

**Comment by root-expert** [comment]
@baurmatt can you rebase and convert that to a patch release?

**Comment by baurmatt** [comment]
@root-expert Done :)

**Comment by root-expert** [comment]
> @root-expert Done :)

Oops you forgot to update the commit message :D

**Comment by baurmatt** [comment]
Ups 🙈 Fixed! :)

**Review by root-expert — APPROVED** [review]

**Pull request merged**
