### PR TITLE
Allow setting unquoted or custom flags on add_headers

### PR DESCRIPTION
**Pull request by itbm**
Allows any combination of add_headers quoting.
_This solves issues highlighted in #991 #992 #1020_ 

**Double Quotes:**
```
add_header => {
    'Access-Control-Allow-Origin'      => '*' , 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" "*";`

**Double Quotes and Unquoted**
```
add_header => {
    'Access-Control-Allow-Origin'      => {'*' => 'always'}, 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" "*" always;`

**Custom Quotes**
```
add_header => {
    'Access-Control-Allow-Origin'      => {'' => '\'*\' always'}, 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" '*' always;`

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
@itbm can you please update test specs to show these conditions? Otherwise, LGTM. Thanks!

**Comment by alexjfisher** [comment]
nginx::location also has an `add_header` parameter. Does its template also need updating? https://github.com/voxpupuli/puppet-nginx/blob/master/templates/server/locations/headers.erb

**Comment by itbm** [comment]
I have changed the sort.each and included the locations/headers.erb file in the others.

**Comment by avillarreal83** [comment]
I wanted to share that when attempting use the add_header in a hiera role, the using the following syntax would add the header to Nginx but the header would not be seen by Nginx due to not specifying the _always_ setting in quotes:

**Initial Puppet settings** 
<code >
add_header:
       Strict-Transport-Security: 'max-age=31536000; includeSubDomains; always'
</code >

### Initial Nginx Results
<code >
add_header "Strict-Transport-Security" "max-age=31536000; includeSubDomains;" always";
</code >

When Nginx is restarted, the header is not recognized. In order to get Nginx configuration to recognize the "always" setting I had to add some extra double quotes to the puppet hiera role I had in place:

**Updated Puppet settings** 
<code >
    add_header:
       Strict-Transport-Security: 'max-age=31536000; includeSubDomains;" "always'
</code >
### Updated Nginx Results
<code >
add_header "Strict-Transport-Security" "max-age=31536000; includeSubDomains;" "always";
</code >

Wanted to share in case anyone else has runs into trying to use the _add_header_ option from the [server resource](https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/server.pp) and experiences this issue. Using the _add_header_ setting from this module was tricky, would be nice to make it easier to use the _always_ setting in future releases.

**Comment by ajcollett** [comment]
Hi.
For all those Heira Users who see the above, here is a better way to do it, for the case above where you need to add a param after the string, and for long strings.
``` yaml
    add_header:
      Strict-Transport-Security: 
        'max-age=<your time>; includeSubDomains': always
      X-Frame-Options: deny
      X-Content-Type-Options: nosniff
      Content-Security-Policy: >-
        default-src 'self'; style-src 'self'; 
        style-src-elem; 
```

**Pull request merged**
