### PR TITLE
Adding some params to the uwsgi template that I needed. And some formating.

### PR DESCRIPTION
**Pull request by jostmart**
Added some params to the uwsgi template that I needed. And some simple formating.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @jostmart, could you add tests to the changes?

**Comment by ffrank** [comment]
Is this safe? Can we be certain that this has no negative impact for existing setups?

**Comment by jyaworski** [comment]
I don't see any problem with this. It looks like it's just adding:

```
+uwsgi_param REQUEST_SCHEME  $scheme;
+uwsgi_param HTTPS           $https if_not_empty;
```

**Comment by ffrank** [comment]
Yes. Is it conceivable that a module user does specifically not want either of those?

**Comment by wyardley** [comment]
@jostmart: will you be able to add tests? If there's no more activity in about a month, this will be closed. Would the fix in #767 work instead? It's generic, but allows adding arbitrary uwsgi_params, which might be more flexible.

I don't deal with nginx / uwsgi together much, but I agree with @ffrank that it might be better not to default to adding them if they're not explicitly set.

**Comment by wyardley** [comment]
@jostmart I think in principle this is fine to add; are you able to add tests?

**Comment by wyardley** [comment]
I'm not even sure that tests are needed here, now that I think about it, but the rename is causing a conflict.

**Comment by ffrank** [comment]
Well, to make this easier: The three added parameters take very sensible values, so I think it should be fine to just merge this.
@jostmart will you be able to take care of those merge conflicts? I'm in favor of just merging once that is done.

**Comment by wyardley** [comment]
@ffrank agreed, but so far, no response (I'm guessing it just needs to be moved to `templates/server`?

Does someone want to take a stab at reworking it and re-submitting (with attribution to the original author)?

**Comment by jostmart** [comment]
Hi I will try to look at it in a couple of days. The change I made have been working great for me since I added it.

**Comment by vinzent** [comment]
@jostmart  any chance to look into rebasing?

**Comment by wyardley** [comment]
If you don't mind, can we pick this up in #1076?

**Comment by wyardley** [comment]
closing via #1076

**Pull request closed without merging**
