### PR TITLE
Don't generate http locations if rewrite_to_https

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
The configuration I'm trying to produce being:

```
server {
  listen 80;
  server_name  host;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name host;

  ssl on;

  location /foo {
  }
  location /bar {
  }
  # ...
```

Locations don't need to be present in both http and ssl servers.

### CODE REVIEW

**Comment by marcofl** [comment]
this is a pretty common use-case. I would +1 for such a implementation, but for now I'm just doing it by passing ssl_port = 443 and listen_port = 443 on the ssl only vhost. then just add a non ssl vhost with the redirect.

**Comment by wyardley** [comment]
@marcofl the current $rewrite_to_https param does do the redirect, @iain-buclaw-sociomantic is just saying that the locations can be suppressed in the non-ssl listener, since all traffic is being redirected.

@iain-buclaw-sociomantic: do you know how to add tests for this? https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.github/CONTRIBUTING.md has some info, and specifically, I think you'd mostly be adding stuff in `spec/defines/resource_vhost_spec.rb` (and / or `resource_location_spec.rb`).

**Comment by wyardley** [comment]
@iain-buclaw-sociomantic: I have reworked this somewhat in #957, hope that's Ok... if you get a chance, take a look and see if it looks reasonable to you.

**Comment by wyardley** [comment]
Superceded by #957

**Pull request closed without merging**
