### PR TITLE
Add autoindex to ssl_header too

### PR DESCRIPTION
**Pull request by bc-bjoern**
Hello,

the option autoindex was missing in server_ssl_header.erb. 

Thanks!

### CODE REVIEW

**Comment by ekohl** [comment]
Could you add a test for this?

**Comment by bc-bjoern** [comment]
May be...

**Comment by bc-bjoern** [comment]
Okay, I can't. 
`   439         describe 'server_ssl_header template content' do
+  440           [
+  441             {
+  442               title: 'should set autoindex',
+  443               attr: 'autoindex',
+  444               value: 'on',
+  445               match: '  autoindex on;'
+  446             }
+  447           ]                                                                                                                                                                        
   448           context 'without a value for the nginx_version fact do' do
   449             let :facts do
   450               facts[:nginx_version] ? facts.delete(:nginx_version) : facts
   451             end
   452             let :params do
   453               default_params.merge(
   454                 ssl: true,
   455                 ssl_key: 'dummy.key',
   456                 ssl_cert: 'dummy.crt'
   457               )
   458             end
   459 
   460             it { is_expected.to contain_concat__fragment("#{title}-ssl-header").with_content(%r{  ssl on;}) }
   461           end
`

**Comment by ekohl** [comment]
Feel free to keep the PR open and add commits to it. If you need help with writing a test we're happy to help.

**Comment by bc-bjoern** [comment]
I do not understand this unfortunately. I guess I need to add it in spec/defines/resource_server_spec.rb in line 439 "describe server_ssl_header template content". But I do not understand how to do it correctly.

**Comment by ekohl** [comment]
It would be very similar to:
https://github.com/voxpupuli/puppet-nginx/blob/ae2af805596703a08349b02d8e859d7125aaafa7/spec/defines/resource_server_spec.rb#L836-L841

That's where we test the SSL part of it. You can copy that one and modify it to autoindex instead of index_files.

**Comment by bc-bjoern** [comment]
Sure, this part is clear more or less. 
```
           [    
             {    
               title: 'should set autoindex',
               attr: 'autoindex',
               value: 'on',
               match: '  autoindex on;'
             }    
           ] 
```
But I didn't managed it to include this into the server_ssl_header section.

**Comment by bc-bjoern** [comment]
Travis says no

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
