### PR TITLE
Remove legacy top-scope syntax

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I'm not sure about updating the changelog, but otherwise :+1:

**Comment by TheMeier** [comment]
@smortex can you re-run the tests?

**Comment by TheMeier** [comment]
Nevermind. The tests will be fixed in https://github.com/voxpupuli/puppet-nginx/pull/1596. To do so I need someone to approve #1595

**Comment by TheMeier** [comment]
rebased

**Pull request merged**
