### PR TITLE
modulesync 1.9.4

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 1.9.4

### CODE REVIEW

**Comment by ekohl** [comment]
```
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: The method driver /usr/lib/apt/methods/https could not be found.
```

This is a regression introduced in https://github.com/puppetlabs/puppetlabs-apt/pull/764

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-apt/pull/775 should fix the regression and fix the integration tests.

**Comment by bastelfreak** [comment]
We need to wait for the next apt release :(

**Comment by ekohl** [comment]
I've restarted the failing jobs to retest with the 5.0.1 release.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
