### PR TITLE
Add ssl_ecdh_curve to server resource

### PR DESCRIPTION
**Pull request by jdmulloy**
Copied from mailhost resource. Needed to get 100 on key exchange on SSL Labs.

### CODE REVIEW

**Comment by jdmulloy** [comment]
I don't think the test failure in Travis have anything to do with my change. It's complaining about the nginx package not working in Arch.

**Comment by juniorsysadmin** [comment]
@jdmulloy #1190 has just been merged, so after a rebase there shouldn't be any more test failures

**Comment by bastelfreak** [comment]
@jdmulloy a patch was merged to master. Can you please rebase?

**Comment by bastelfreak** [comment]
rebased it

**Pull request merged**
