### PR TITLE
Release prep for 3.0.0

### PR DESCRIPTION
**Pull request by genebean**
#### Pull Request (PR) description

Updates docs and metadata in preparation for the 3.0.0 release.

### CODE REVIEW

**Comment by genebean** [comment]
@bastelfreak happy to rebase if you want to pull in the other PR we were chatting about first

**Comment by ekohl** [comment]
I'd like to merge https://github.com/voxpupuli/puppet-nginx/pull/1385 if we're doing a major version.

**Comment by bastelfreak** [comment]
@genebean #1385 got merged, please rebase against master and regenerate the changelog.

**Comment by attachmentgenie** [comment]
i would like to get #1442 in too

**Comment by attachmentgenie** [comment]
#1442 got merged too

**Comment by genebean** [comment]
I am working to update this PR today.

**Comment by genebean** [comment]
I believe this is ready to go now.

**Review by alexjfisher — APPROVED** [review]

**Pull request merged**
