### PR TITLE
Add RedHat 8

### PR DESCRIPTION
**Pull request by stevenzerbe**
#### Pull Request (PR) description
Enable RHEL8 operatingsystem_support

### CODE REVIEW

**Comment by stevenzerbe** [comment]
@ghoneycutt requested I ping them for review.

**Review by ekohl — CHANGES_REQUESTED** [review]
Please also add CentOS 8 to the list of supported OSes. That gives us acceptance tests.

**Comment by stevenzerbe** [comment]
> CentOS 8 added to operatingsystem_support for testing.

**Comment by ghoneycutt** [comment]
Merged as the spec tests are passing and the failing acceptance tests were already failing and are unrelated to this change.

**Comment by smortex** [comment]
FYI, the passenger repo is *really* not working on CentOS Stream:

```
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides rubygem(rack) needed by passenger-6.0.14-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Will remove support for it in #1502.

**Pull request merged**
