### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by ekohl**
See individual commits:
* Remove double spacing
* Move error_log to the http context
* Strip line endings in mime.types
* Use more Puppet 4 types
* Propery handle ${client_body,proxy}_temp_path

### CODE REVIEW

**Comment by alexjfisher** [comment]
‘Various Updates’ is going to be too vague for the changelog. Could you update the PR title or split this into separate PRs?

**Comment by ekohl** [comment]
As you can see the commits are cleanly split with the intention of separating. I just wanted to push my changes so they weren't just on my desktop :)

**Comment by ekohl** [comment]
Replaced by:
* https://github.com/voxpupuli/puppet-nginx/pull/1251
* https://github.com/voxpupuli/puppet-nginx/pull/1252
* https://github.com/voxpupuli/puppet-nginx/pull/1253
* https://github.com/voxpupuli/puppet-nginx/pull/1254
* https://github.com/voxpupuli/puppet-nginx/pull/1255

**Comment by alexjfisher** [comment]
@ekohl I figured that was probably the case and you just wanted to show off what you'd been up to. :)

**Comment by ekohl** [comment]
Something like that, something like a backup :)

**Pull request closed without merging**
