### PR TITLE
Add create_resources for nginx_snippets

### PR DESCRIPTION
**Pull request by aba-rechsteiner**
#### Pull Request (PR) description

add create_resources for nginx_snippets and nginx_snippets_defaults

### CODE REVIEW

**Comment by kenyon** [comment]
Can you rebase to remove the merge commit? Also, can you add Puppet Strings docs for these new parameters?

**Comment by aba-rechsteiner** [comment]
> Can you rebase to remove the merge commit? Also, can you add Puppet Strings docs for these new parameters?

sorry, sure i will adjust that

**Review by kenyon — CHANGES_REQUESTED** [review]
The new parameter docs should go in the comments in `init.pp`. `REFERENCE.md` is automatically generated from those comments, which is called Puppet Strings documentation. https://puppet.com/docs/puppet/7/puppet_strings.html

**Comment by aba-rechsteiner** [comment]
i don't quite understand, other parameters like for example nginx_locations are also not described in init.pp

**Comment by root-expert** [comment]
> i don't quite understand, other parameters like for example nginx_locations are also not described in init.pp

They aren't but they should have been. We are trying to add docs for every new parameter :smile:

**Review by kenyon — APPROVED** [review]

**Comment by root-expert** [comment]
I think it's ok to merge until we fix the CI.

**Comment by aba-rechsteiner** [comment]
@root-expert or @kenyon can you create a new v3.4.0 Release?

**Pull request merged**
