### PR TITLE
Add access_by_lua_file server directive.

### PR DESCRIPTION
**Pull request by oc243**
This lets you control access to an nginx server using lua

### CODE REVIEW

**Comment by dol** [comment]
The [lua-nginx-module](https://github.com/openresty/lua-nginx-module#directives) provides approx. 70 directives. `access_by_lua_file` is only one of them. I suggest adding a few more or separate them into it's own resource that inherits from the server resource. This makes it easier to update the lua-nginx-module directives more independent.
The [OpenResty](https://openresty.org/) project bundles quite a few [components](https://openresty.org/en/components.html). All the non Lua based components have their own nginx directives.

At the current state non default directives can be loaded via the different cfg_prepend/append possibilities.

**Comment by vinzent** [comment]
@dol defined types can't inherit in puppet. Or what you think of by inheriting?

**Comment by dol** [comment]
@vinzent By inherit i meant class inheritance. But since you pointed out, thats not possible with defined type. My bad.

**Comment by oc243** [comment]
@dol what do you suggest doing with this PR?

**Comment by dol** [comment]
@oc243 A proper integration needs some planing. For example `access_by_lua_file` could be defined in the following context: `http, server, location, location if`. This would imply to adding access_by_lua_block to different resources. In addition there is the related 'access_by_lua` and `access_by_lua_block` directive, that needs to be offered as well.

Regarding this PR I would close this PR without merging and would transfer the findings and comment into it's own issue/feature request.

**Pull request closed without merging**
