### PR TITLE
Add expires option to the location class

### PR DESCRIPTION
**Pull request by Snowmean**
I've added "expires" option to the locations class. 

We are using that option in our servers configurations, and it helps us to reduce amount of traffic significantly due to different cache expiration time for static content like jpg, css, js etc... So I think it would be nice to have it in public module as well.

### CODE REVIEW

**Comment by 3flex** [comment]
@Snowmean sorry for the huge delay. Can you please rebase on master, and squash this down to a single commit for merging?

Adding new tests would also be very useful and speed up the merging process once updated. Thanks!

**Comment by wyardley** [comment]
Hi --
This still hasn't had a rebase, and has no tests. If there's no activity in a month, we'll close this PR.

**Comment by Snowmean** [comment]
You can close it now, I have no time for that now, and I doubt I will have it anytime soon.

**Comment by wyardley** [comment]
Ok, thanks. It's pretty simple and seems like it could be useful (even though there are workarounds), so I will take a stab at updating it if I get some time.

**Comment by wyardley** [comment]
Replacing this for you in #924 (with test / rebase).

**Pull request closed without merging**
