### PR TITLE
add ubuntu1804 as supported OS

### LINKED ISSUE #1307: Support for Ubuntu 18.04?
Do we have plan to support Ubuntu 18.04?

### PR DESCRIPTION
**Pull request by Dan33l**
#### This Pull Request (PR) fixes the following issues

Fixes #1307

### CODE REVIEW

**Comment by dhoppe** [comment]
@Dan33l I think you need to add ```bionic``` to the [array](https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/params.pp#L110).

**Comment by Dan33l** [comment]
@dhoppe thank you for the comment.
I pushed the the updated array.

**Comment by LongLiveCHIEF** [comment]
I'm not sure about the package source failures. My usage of the module on 18.04 disables the package management since I provide my own source repos and management for that.

**Comment by dhoppe** [comment]
@LongLiveCHIEF At least the latest commit fixed the unit tests. The current error message is related to the acceptance tests and Passenger.

**Comment by Dan33l** [comment]
The test get the output of command `dpkg -s nginx | grep ^Maintainer ` And with the current setup on ubuntu18.04 it is getting `Maintainer: Sergey Budnevitch <sb@nginx.com>`.

Is it normal or not ?

**Pull request merged**
