### PR TITLE
manage repo for Debian 10

### PR DESCRIPTION
**Pull request by octomike**
#### Pull Request (PR) description

Nginx official repo supports Debian 10, see here: http://nginx.org/packages/debian/dists/

#### This Pull Request (PR) fixes the following issues

Systems that upgraded to buster already are not receiving updates for nginx right now.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@octomike ping :)

**Comment by anarcat** [comment]
i can confirm that this module works on Debian 10, for what that's worth.

**Comment by bastelfreak** [comment]
@octomike can you please rebase?

**Comment by bastelfreak** [comment]
@octomike can you add the acceptance tests for debian 10 to the .travis.yml and also add Debian 10 in the metadata.json?

**Comment by octomike** [comment]
Yes, I'm testing this right now and will push the changes later.

**Comment by octomike** [comment]
Just so I understand things: For `.sync.yml` to generate a fresh `.travis.yml` someone needs to run modulesync (ideally including https://github.com/voxpupuli/modulesync_config/pull/627/commits) on this repo and commit. Is that correct?

**Comment by bastelfreak** [comment]
the process is a bit, uhm, not perfect. So msync parses the .sync.yml and generates the acceptance test entries in .travis.yml. Issue here is that we need those tests to pass before we merge this PR. you can just copy and paste the current debian9 blocks in the .travis.yml and rename them to debian10. That will do it for now.

**Pull request merged**
